const radarZoneStyles = () => ({
    wrapperRadarZone: {
        background: "linear-gradient(transparent, 45%, #000000)",
        position: "absolute",
        bottom: 0,
        width: "100%",
        height: 54,
        left: "50%",
        transform: "translate(-50%, 0)",
    },
    lineWithContent: {
        width: "100%",
        height: "100%",
        overflow: "hidden",
    },
    radarItemWrapper: {
        position: "absolute",
        top: "0.75rem",
        left: "auto",
        width: 30,
    },
    radarItemWrapperWay: {
        position: "absolute",
        top: "0.75rem",
        left: "auto",
        width: 30,
    },
    wrapperContentItems: {
        border: "none",
        cursor: "pointer",
        outline: "none",
        display: "block",
        width: "100%",
        height: "100%",
        background: "transparent",
        padding: 0,
        "& img": {
            width: "100%",
        },
    },
    wrapperContentItemsPan: {
        border: "none",
        cursor: "pointer",
        outline: "none",
        display: "block",
        width: "100%",
        height: "100%",
        background: "transparent",
        padding: 0,
    },
    contentItems: {
        width: "100%",
    },
    contentItemsWay: {
        width: "80%",
        transform: "rotate(-225deg)",
    },
    iconForPreviousPan: {
        width: "80%",
        transform: "rotate(-225deg)",
    },
    northWrapper: {
        position: "absolute",
        top: -88,
        right: 0,
        borderRadius: "50%",
        width: 50,
        transition: "background 200ms",
    },
    northIndicate: {
        width: "100%",
        opacity: 0.8,
    },
    wrapperThumb: {
        position: "absolute",
        top: -241,
        left: "50%",
        transform: "translate(-50%, 0)",
        width: 326,
        padding: 2,
        border: "1px solid #ffffff",
        height: 206,
        transition: "opacity 150ms, visibility 150ms",
        "&::after": {
            content: "''",
            position: "absolute",
            top: "100%",
            left: "50%",
            transform: "translateX(-50%)",
            width: 0,
            height: 0,
            borderTop: "12px solid #ffffff",
            borderLeft: "11px solid transparent",
            borderRight: "12px solid transparent",
            borderBottom: "15px solid transparent",
        },
    },
    thumbContent: {
        width: "100%",
        height: "100%",
    },
    showThumb: {
        opacity: 1,
        visibility: "visible",
    },
    hideThumb: {
        opacity: 0,
        visibility: "hidden",
    },
    badgeRoot: {
        top: -5,
        right: "50%",
    },
    setLook: {
        display: "block",
        position: "absolute",
        right: 4,
        top: -35,
        width: 40,
        border: "none",
        padding: 0,
        background: "transparent",
        cursor: "pointer",
        "& img": {
            width: "100%",
            height: "100%",
        },
    },
    leftSortContent: {
        zIndex: 1,
        width: 37,
        height: 30,
        position: "absolute",
        top: "0.75rem",
        transition: "left 150ms cubic-bezier(1, 0.9, 0.32, 1.80)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        "& button": {
            outline: "none",
            border: "none",
            cursor: "pointer",
            background: "transparent",
            display: "inline-block",
            width: "100%",
        },
        "& img": {
            width: "100%",
            height: "100%",
            verticalAlign: "middle",
        },
        "& span": {
            color: "white",
            display: "block",
            position: "absolute",
            fontSize: "0.9rem",
            top: "50%",
            left: "56%",
            transform: "translate(-50%, -50%)",
        },
    },
    showLeftIndicate: {
        left: -3,
    },
    hideLeftIndicate: {
        left: -53,
    },
    rightSortContent: {
        zIndex: 1,
        width: 37,
        height: 30,
        position: "absolute",
        top: "0.75rem",
        transition: "right 150ms cubic-bezier(1, 0.9, 0.32, 1.80)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        "& button": {
            outline: "none",
            border: "none",
            cursor: "pointer",
            background: "transparent",
            display: "inline-block",
            width: "100%",
        },
        "& img": {
            width: "100%",
            height: "100%",
            verticalAlign: "middle",
        },
        "& span": {
            color: "white",
            display: "block",
            position: "absolute",
            fontSize: "0.9rem",
            top: "50%",
            left: "42%",
            transform: "translate(-50%, -50%)",
        },
    },
    showRightIndicate: {
        right: -3,
    },
    hideRightIndicate: {
        right: -53,
    },
});

export default radarZoneStyles;
